### ISSUE TITLE
Default `python` and `pip` commands in docker to py3

### ISSUE THREAD

**Issue by stevenle** [grow/grow#1092]
With the `1.0.0` release, we should update any references of `python` and `pip` to use py3 equivalents.

Currently: `python` defaults to `python2` and `pip` is not available (although `pip3` is).

**Comment by Zoramite** [comment]
I think that it would be handy, I don't know if it is feasible:

https://wiki.ubuntu.com/Python/3

They mention that they are not going to make the default for `python` be `python3` because this is not going to happen: "/usr/bin/python will point to Python 3. No, this is not going to happen (unless PEP 394 advocates otherwise, which is doubtful for the foreseeable future)."

**Comment by stevenle** [comment]
Alright thanks, I'm going to close this.
