### ISSUE TITLE
Feature: Add live flag to documents

### ISSUE THREAD

**Issue by WillsB3** [grow/grow#196]
Sometimes a document needs to exist in the repository but not be rendered during build. i.e. the document should just be totally ignored by Grow.

This has arisen from some work that had been merged into our master branch which, at the last minute, we were asked to postpone the launch. The only way I know to do this currently, is to delete the yaml file, however this means that when we need to actually launch in a few days/weeks we'll have to go hunting for the commit which deleted the yaml and revert it.

Perhaps having a `$live` property on documents that defaults to `true`, but can be set to `false` if required  would be a good idea?

**Comment by jeremydw** [comment]
I think something like this could be a good idea, but it'd be worth it to take a second to think about naming. I also want to be careful about how much "workflow" we introduce into the system versus relying on Git for that.

We recently added a flag [1] to `static_dirs` named `dev` that, when true, only serves files matching that rule on the development server. We chose "dev" because that's exactly when the files will be served -- only on the dev server. When `grow build` is run (incl. `deploy`) -- those files aren't built. We could do the same thing with `$dev` on content documents. What do you think should happen when `g.doc(...).url` is used on a document where `$dev` is true? Fail on build but work on the dev server? That seems like it could work to me -- that'd prevent folks from building dev files as that would raise an error (the document wouldn't exist).

Separately, another way to disable building the file without any changes to Grow is just to use the following `$path: ""`. This effectively sets the document's serving path to an empty string, which prevents it from being built. (Documents without URL paths aren't built, of course.)

[1] https://github.com/grow/grow/commit/bdb6c75f2e88eac4b7c8207ca6b7dbeedac1bef4

**Comment by WillsB3** [comment]
Just tried using this path trick again and seem to be getting an error when setting the path to empty string:

> File "my-project/lib/python2.7/site-packages/grow/server/manager.py", line 36, in print_server_ready_message
    root_path = home_doc.url.path if home_doc else '/'
AttributeError: 'NoneType' object has no attribute 'path'

This is with Grow 0.2.1.

**Comment by Zoramite** [comment]
@WillsB3 That error seems to be because it cannot find the default homepage. What do you have for the `home` value in your podspec? It needs to be something that has a serving path if you are using it as the home document.

**Comment by WillsB3** [comment]
Ah - sorry - You're right. I hadn't updated `home` in podspec.yaml.

**Comment by Zoramite** [comment]
You should be able to now get this effect using the new syntax to disable it based on the environment:

    $path: "/somewhere"
    $path@env.prod: ""

Would cause it to be rendered everywhere but the `prod` env.
