### ISSUE TITLE
Can't create custom jinja2 extension

### ISSUE THREAD

**Issue by kandeshvari** [grow/grow#198]
Trying to implement get_year extension due to documentation: https://grow.io/docs/extensions/#jinja2-extensions and get an error:

```
Error: Could not import 'extensions.getyear.GetYear': must use dot syntax relative to the pod root
```
in project root:
```
extensions/__init__.py
extensions/getyear.py
podspec.yaml
...
```

podspec.yaml:
```
...
extensions:
  jinja2:
    - extensions.getyear.GetYear
...
```

content of getyear.py:
```python
import datetime
import jinja2

def get_year(value):
    tm = datetime.datetime.now()
    return tm.year

class GetYear(jinja2.Extension):
    def __init__(self, environment):
        super(GetYear, self).__init__(environment)
        environment.filters['getyear'] = get_year
```

System's `jinja2` haven't `Extension` class. It seems like `jinja2` is internal growsdk's package, but import fails. Documentation example also fails with the same error. Can you provide me working example?

**SOLVED:**
need to `import jinja2.ext` instead of `jinja2`. Please update documentation.

**Comment by jeremydw** [comment]
Hi there -- thanks for the detailed report. :)

I think your report uncovered two things: one, a documentation error. As you identified, you should subclass `jinja2.ext.Extension` instead of `jinja2.Extension`. I'll go ahead and fix that documentation issue ASAP.

The other error that occurred was that we don't bubble up any syntax errors that might exist in the user-authored extension itself. I filed https://github.com/grow/grow/issues/199 to track the fix.

**Comment by kandeshvari** [comment]
No problem ;)

also add to documentation that empty file `extensions/__init__.py` SHOULD be present.

**Comment by jeremydw** [comment]
Yep, all set! https://github.com/grow/grow.io/commit/5e8c203a1a9fdac91afbbc356e4686ec9e9e268b Thanks!

**Comment by kandeshvari** [comment]
Maybe you can alsp replace `ClassName` with real example class name `Triplicate`?

`super(ClassName, self).__init__(environment)` -> `super(Triplicate, self).__init__(environment)`

**Comment by jeremydw** [comment]
Thanks for the suggestion, done: https://github.com/grow/grow.io/commit/1b5a4c38ba8ca1596f4f06cb603b7f98b7264194
