### ISSUE TITLE
Allowing documents to declare themselves as having _no_ locales

### ISSUE THREAD

**Issue by stucox** [grow/grow#214]
Suggested on #206, to facilitate locale-specific content without overriding (composition rather than inheritance), e.g.:

```yaml
---
$locale: null
foo: base
---
$locale: en
foo: en_foo
---
$locale: fr
foo: fr_foo
---
```

---

My 2 cents: I don’t think this is necessary.

It’s rare you’ll have a document with completely different content in different locales*.

* When content _IS_ completely different, one could argue these are actually different documents, so should be separate files.
* When there is some overlap, it makes sense to have the overlapping content in the base document and mark that document as having the locales for which the content overlaps.

_* assuming documents are always authored in the same language, e.g. US English, and translation is handled entirely by PO files — which is the pattern followed in my projects._

So I don’t think there’s a good real-world use-case.

---

Related question:

**Should a document part be able to declare a locale which _isn’t_ declared in the base document?**

* If we allow `$locale: null`, the answer to this has to be _yes_.
* Allowing this is more consistent with the fact that a collection’s blueprint can declare locales which aren’t declared in podspec, a document can declare locales not declared in the blueprint, etc
* However, this might make documents less readable: it becomes less obvious which locales this page will be built for (5 locales might be declared at the top, but another declared in a later part).
* Allowing this might also complicate Grow’s internal implementation.
* If Grow _disallowed_ this, it could catch some authoring mistakes.

Maybe this is another case where projects should be able to choose which pattern they prefer, either with a setting, or with a custom test?

**Comment by jeremydw** [comment]
With #267 submitted, documents and collections can now disable localization (e.g. declare no locales) with the following syntax:

```
$localization:
  locales: []
```

If `$localization: locales` is omitted, the document or collection will fall back to its parent. In the case of a document, the collection's `$localization` will be used, and in the case of a collection, the podspec's `$localization` will be used.

Note there is not presently any defined `$localization` behavior for subcollections, so the document -> collection -> podspec fallback behavior is adhered to universally.

For content overrides, one can override content in the default locale in the following manner:

```
foo: bar
foo@en_US: bar for en_US
foo@de: bar for de
```

```
# en_US
{{doc.foo}} -> "bar for en_US"

# de
{{doc.foo}} -> "bar for de"

# fr
{{doc.foo}} -> "bar"
```

When implementing locale validation (i.e. ensuring that documents and document parts only define locales that they are localized to either in the base part or in the collection), I initially found too many cases of documents without blueprints and other partial data documents, so I decided against implementing any sort of additional strong locale validation because of the risk of introducing false negatives related to sub-folders within collections.

I hope this will be sufficient to close up this issue but please re-open it if we need to discuss more -- especially if you want to revisit the validation issue.
