### ISSUE TITLE
After deployed, cannot access font in static dir

### ISSUE THREAD

**Issue by bluzky** [grow/grow#273]
When build project, it automatically appends hash string to the font file name.
So that I cannot access the font file in my css file.
How can I fix this?

**Comment by jeremydw** [comment]
Hi @bluzky — the immediate alternative is to remove the `fingerprinted: true` lines in `podspec.yaml` so that your assets are not fingerprinted.

The way that we handle this on most projects is run the generated CSS files through a Gulp task that adds the fingerprint to static files in the CSS files. I'll send you an example of this when I get a chance.

We're also thinking about adding a builtin that would do this automatically, without the Gulp task. I will keep you updated on that too.

**Comment by bluzky** [comment]
thank you.
It will be great if it can process this automatically

**Comment by JaredSartin** [comment]
Sorry to bring this back from the dead - how/where was this solved, or was it just closed?

**Comment by Zoramite** [comment]
The issue was that the font file was inside a static directory that was configured to be fingerprinted. There are two ways to fix this: 1) use the fingerprinted filename (which would be very fragile) 2) move the font to a different static directory that is not fingerprinted and reference the file from there.
