### ISSUE TITLE
 Pretty print html / BeautifulSoup 

### ISSUE THREAD

**Issue by kezlya** [grow/grow#286]
Would be nice to have python BeautifulSoup added to the grow. So the final output is pretty printed html

Posible implimentation:
* Add extra parameter to Pod.dump() like **prettify_html=False**
```bash
def dump(self, suffix='index.html', append_slashes=True, prettify_html=False):
```
* Add config variable to podspect.yaml to switch it on/off

**Comment by jeremydw** [comment]
Yea, looks like some sort of HTML prettification is desired.

I think that the "view source" output in the browser should match what gets written to the filesystem (in order to stay consistent with the "no magic" rule), so I'm hesitant to make this a kwarg to `dump`. Some other discussion is in this bug: https://github.com/grow/grow/issues/51

**Comment by kezlya** [comment]
BeautifulSoup takes a lot of overhead. Will use jinja2 custom extension described in this [comment][1]
[1]: https://github.com/grow/grow/issues/51#issuecomment-243600665
