### ISSUE TITLE
babel format_currency() doesn't work with grow

### ISSUE THREAD

**Issue by juliepranger** [grow/grow#291]
leaves the user with the error:

**UnknownCurrencyFormatError: "'standard' is not a known currency format type"**

Something to note -- format_currency works in Terminal, but not in the browser/with Grow.

Have tried to pip install grow, and add babel to vendor extensions, with the same error message resulting. Using python's locale.currency ( https://docs.python.org/2/library/locale.html ) in the meantime.

**Comment by jeremydw** [comment]
I can confirm that the fix for PyInstaller on the build machine also fixes this problem, so I'm going to close this out as this will be fixed in the next release of grow. (https://github.com/grow/grow/issues/302)

In https://github.com/grow/grow/issues/302 we're having a discussion about whether/how to include the `babel.numbers` module directly as a built-in filter/global in Grow's Jinja environment, and then you would not have to use an extension to get this functionality.
