### ISSUE TITLE
Insert partial support inside content files

### ISSUE THREAD

**Issue by NetLancer** [grow/grow#301]
Say there's /about.html document and much-much code, and to clear it up & maintainable I want to move part of html-code & break that to small partials to be included when/where needed (into content pages).
Things like {% include 'path/to/partial.html' %} which fork well in template documents don't work within content .md/.html files.
Is that possible at all? Please help dummy

**Comment by NetLancer** [comment]
All I need is something like this:  http://www.sitebox.io/articles/partial-method
Either if there's an alternative way to implement this trick please give me the clue.
(Currently I'm working with Grow's 'base' theme)
Don't just ignore me guys or I'll keep opening new issues on it over & over :)

**Comment by NetLancer** [comment]
So dynamic partial-including (with content pages) is not possible, as no answer came so far

**Comment by jeremydw** [comment]
Hi @NetLancer -- we are very busy with project deadlines right now which is why you might not be hearing anything from us. Plus, this is a support request and not exactly a bug report or an issue, so please be patient. :)

Grow supports Jinja's template language. You can use it to include other documents in either your views or your content files (formatted as markdown or html). You can use the `{% include %}` tag to include anything in your site, or the `!g.yaml` yaml constructor to include one yaml file inside another.

If you have a code sample you can post it here and we can provide some help when we have some time.

**Comment by NetLancer** [comment]
[grow-sdk_rendered.png](https://postimg.org/image/ijd1esfun/)
renders as a bare text.  
I'm using 'base' grow's theme (as I've already built it up a little, http://uzlander.site50.net/).

**Comment by NetLancer** [comment]
Real poor community support, has anyone used grow's base template to build from scratch (which I did)so far ? Content files don't know what templating tags are, may be it is only my case, jeremydw please giveme advice

**Comment by uxder** [comment]
Hey @NetLancer,

How are you outputting your .md files with those include tags?  Since it came out a string, I assume you might have something like:

`{{doc.html|safe}}`

You can try:

`{{doc.html|render|safe}}`

**Comment by NetLancer** [comment]
Doesn't matter renders the way it is (my case is *.html document although I've tried with *.md too)
https://s22.postimg.org/zaivlfhrl/2016_oct_14.png

**Comment by uxder** [comment]
I wasn't suggesting to replace your {% include %} so I think you misunderstood me.  Your problem seems to be that you are trying to run jinja code in .html docs.   If you are working off of the base theme, try updating [this line](https://github.com/growthemes/base/blob/master/views/base.html#L47): to `{{doc.html|render|safe}}`

If that doesn't work, do you think you can provide some code of that page and its parent page (or base template)?  Without some sample code to view, it's really difficult to help support you on this.

**Comment by NetLancer** [comment]
Splendid, this one worked! Thanx a lot uxder. But what then {{doc.html|safe}} (without 'render') really does ?

**Comment by jeremydw** [comment]
Just to clarify this - what `{{doc.html}}` does is return the "HTML-formatted" output for the corresponding content document. For a Markdown file, this will return the document's body rendered as Markdown. What `{{doc.html}}` will not do, by default, is render the Document with any sort of Jinja processing or Jinja context.

The `|render` filter will treat its input as a Jinja template, and then render it. So, if you're using Jinja variables within your Markdown document, you'll want to pipe `{{doc.html}}` to `|render` so that Grow knows to process the Markdown as a Jinja template, and not just HTML. That's how it works at the moment, anyway.
