### ISSUE TITLE
Pug (Jade) as custom preprocessor

### ISSUE THREAD

**Issue by cekvenich** [grow/grow#304]
I could argue that Pug (Jade) is the most popular preprocessor (after Sass, which you have).

And that is what we use. How would I go about implementing
http://grow.io/docs/extensions/#custom-preprocessors ?

Normally I run some node code. So in that template how would I execute a node task? 

Cheers,
Vic

**Comment by jeremydw** [comment]
Hi! How are you thinking about using Pug with a Grow project? We have a built-in Gulp preprocessor that automatically runs Gulp tasks for you during `grow run` and `grow build`. A quick Google search yields `gulp-pug` which seems to be a Gulp plugin for pug.

https://www.npmjs.com/package/gulp-pug
http://grow.io/docs/preprocessors/#gulp

I've never used pug before but this could be a logical way for you to use it with a Grow project. Plus, Gulp will ingest whatever node code or node tasks you throw at it.

If you were looking for Grow to support rendering static HTML pages using Jade templates instead of Jinja templates -- that sort of feature isn't available right now as Grow is pretty tightly-coupled to the Jinja environment. It's not out of the question that we could add support for other template engines in the future, but we wouldn't be able to implement something like that right away as there are a few more pressing features to develop related to workflow.

Let me know if this answer is sufficient or if you're looking for more tips.

**Comment by NetLancer** [comment]
How about using pug with content (page/post) files? I mean jinja seems doesn't watch things inside 'content' anyway and pug would be a great help for rapid html writing alongside with common 'unclosed-tags' problems solved (my case :)). Would you consider providing it as an option? (I'm not an advanced dev)
