### ISSUE TITLE
Custom translations between views

### ISSUE THREAD

**Issue by drGrove** [grow/grow#318]
Currently when a translation is imported via `grow import_translation` you can specify the locale and the source file. If, for instance, we have a special translation for something with the same string id (see below), we would like the initial text to still be in english. In general, I can understand how overriding these translations would make the most sense (since normally that means a better translation has come along). And what we currently do is place the Japanese text directly into the yaml. Which makes editing the yaml for that instance rather unnerving.

EX with current implementation
`grow import_translation --locale=ja_JP --source /path/to/translation.po`

``` po
# translations/ja_JP/LC_MESSAGES/messages.po

#. 'Plan B' on both pages has been updated, this is not as expected
#: /content/pages/home.yaml /content/pages/legal.yaml
msgid "Plan B"
msgstr "戦略B"
```

Ex with what i'm hoping would work, but does not currently:
`grow import_translations --locale=ja_JP --path=/content/pages/legal.yaml --source /path/to/translation.po`

``` po
# translations/ja_JP/LC_MESSAGES/messages.po

#: /content/pages/home.yaml
msgid "Plan B"
msgstr "次のプラン"

#. Because of this being legal, we want the english to say 'plan B' since that makes sense in english
#. But use 'strategy B' in Japanese
#: /content/pages/legal.yaml
msgid "Plan B"
msgstr "戦略B"
```

Currently grow will use The first one since it's the first msgid that it finds, and doesn't take the paths into consideration. Is this a babel thing?

---

What this means is that currently we'd have to do something like this:

``` yaml
# /content/pages/home.yaml
#.
#.
#.
copy@: "Plan B"
```

``` yaml

---
# /content/pages/legal.yaml
locales:
  - en_US
  - ja_JP

copy@: "Plan B"

---
$locale: ja_JP

copy@: "戦略B"
```

**Comment by jeremydw** [comment]
What you're referring to (the internal path where the string is used) is just a gettext comment and that doesn't carry any meaning for the context/implementation of the translated string -- it's strictly for the developer or the translator to know where the string is located in which file.

That said, gettext does support a `msgctxt` (context) flag that's meant for exactly what you want -- two identical strings with different meanings that should/may be translated differently depending on the context. Jinja doesn't seem to have built in support for this but we are tracking the issue here -- https://github.com/grow/grow/issues/284

**Comment by Zoramite** [comment]
it doesn't really work for importing translations, but in the cases where you want to have the text translated differently in the two cases you could do something like this:

```
# /content/pages/home.yaml
copy@: Plan B
copy@ja_JP@: 戦略B
```
