### ISSUE TITLE
Ability to specify version in call to https://install.growsdk.org

### ISSUE THREAD

**Issue by jamesspencer** [grow/grow#336]
(Creating an issue against grow/grow as I can't find a project for the growsdk.org site.)

We want to pin Grow's version in our app and would like some reliable way of programatically installing a specific version of the Grow library and SDK.

We cannot use [the install script](https://raw.githubusercontent.com/grow/grow/0.0.66/install.py) to install a specific version as the install script always grabs the latest release based on [GitHub's API response](https://api.github.com/repos/grow/grow/releases). It would be great if this was modified to allow a specific version of the Grow SDK to be installed.

Currently, you can navigate the releases page and finding the correct SDK version for your platform then doing the download, unzip, move to `bin`/add to path dance (or build from source). Since you've spoiled us with a nifty install script, this now feels like too much effort ;)

**Comment by jamesspencer** [comment]
AFAICT this would need:

Updates to https://install.growsdk.org/ to allow specifying a particular version of https://raw.githubusercontent.com/grow/pygrow/master/install.py

Updates to https://raw.githubusercontent.com/grow/pygrow/master/install.py to install a hard-coded SDK release.

Perhaps more effort than it's worth?

**Comment by jeremydw** [comment]
Agreed, that's a ton of effort. Instead of using the installer, I would recommend just using `pip`. For example, `pip install grow==0.0.67` to freeze your Grow installation to v0.0.67.

That said, when using `pip`, the setup is a bit more complicated because you need virtualenv, etc. and you lose the benefits of the installer.

Would the `pip` approach be sufficient for you, or would you like a way to use the installer to freeze Grow to a specific version? Note we're also exploring adding grow to `npm` and/or `brew`, but just trying to get more information on your use case.

Thanks!

**Comment by jamesspencer** [comment]
I'm mainly after a way to script installation of the versioned command line tools in order to automate Grow installs for a bunch of projects with varying dev cycles. Would like to pin projects to a Grow version and upgrade as needed.

The `pip` route should work well if we maintain our own set of Grow commands or leave pointers to the Grow CLI. Virtualenv is a plus for us.

The NPM option with an executable for the CLI would be exceptionally useful IMO!

**Comment by jamesspencer** [comment]
Ah, my mistake--the pip installed version does provide the CLI! This works for us. Thanks!
