### ISSUE TITLE
Release in PyPI

### ISSUE THREAD

**Issue by aplanas** [grow/grow#356]
The last release via github is now 0.0.68, but in PyPI is 0.0.67. I suggest to update both close in time, because some workflows and installations use the PyPI package directly.

**Comment by jeremydw** [comment]
Done: https://pypi.python.org/pypi/grow/0.0.68

We are working on automating our release process with GitHub tags to keep everything moving forward more easily and released in both places simultaneously.

**Comment by hieu-n** [comment]
Grow version on PyPi often lags behind. Should we document an alternative way to install directly from the github repo? For an example:

`$ pip install https://github.com/grow/grow/archive/master.zip`
or
`$ pip install https://github.com/grow/grow/archive/0.1.0.zip`

I know there is `curl https://install.growsdk.org | bash`, but I feel safer to use `pip install` instead of running a bash script.

**Comment by Zoramite** [comment]
We are still technically working on finishing the `0.1.0` release (although it is tagged it will be recreated tomorrow).

It is the first time that we are using the CI to build the release binaries so we are doing some extra testing to verify that the builds are working correctly. Plus we have an issue that we are working on fixing (#391) that should be finished tomorrow and the 0.1.0 tag will be redone. So, sorry that the latest isn't in PyPi yet. It will get there soon once we have verified that everything is working correctly.
