### ISSUE TITLE
Ability to set a deployment target specific "base path"

### ISSUE THREAD

**Issue by WillsB3** [grow/grow#374]
Hey,

I'm working on a replacing an existing (non-Grow) website and have a staging environment that lives at a different base path to the production site, e.g:

**Live:** www.mywebsite.com
**Staging:** www.anotherdomain.com/staging/
**Dev:** www.anotherdomain.com/dev/

From a quick dig into the docs and the code, it looks like it's not possible to specify a differing "base path" (the `/staging/` and `/dev/` parts) for our staging/dev environments. I did think that I might be able hacking around this by setting the `host` property of the `env` config to `mywebsite.com/dev` but haven't tested this, and of course this would break if you needed to specify a custom port as the URL would then build out as (for example) `mywebsite.com/dev:8082`.

What are your thoughts/feelings on adding an additional property to the `env` dictionary of a deployment config?

I know hosting dev/staging sites on a different/sub-domain is obviously the preferred solution, but I'm not sure that's an option in my case.

**Comment by WillsB3** [comment]
OK - we've just moved to serving the different envs on separate sub domains.

Feel free to invalidate if you think supporting this is not worth it :)

**Comment by jeremydw** [comment]
Hey - Grow does support different `out_dirs` on a per-deployment (local deployment) basis. However, Grow does not support different "root paths" on a per-deployment basis because part of the philosophy is that the URL paths in development and staging should always mirror production / the deployed environment.

So, you could have `grow deploy dev` and `grow deploy staging` deploy to two different directories, always use relative links, and then you could configure your staging server to serve from those two different directories, respectively. That would probably get the results you need.

Another idea I've been toying with is the ability to specify the podspec file - so you could easily have multiple podspec files for your project depending on the build/environment.

The multiple subdomain approach sounds like the right idea to me though. If you think it'd help feel free to ping me privately and describe your staging environment/use case a little more and I can let you know what I think!

**Comment by WillsB3** [comment]
> Another idea I've been toying with is the ability to specify the podspec file - so you could easily have multiple podspec files for your project depending on the build/environment.

This also crossed my mind - but then no doubt you'll update something in one and forget to do it in the other, and unless there's some sort of overriding rather than just flat out completely separate files per env it could get confusing. 

The relative URL is probably the best workaround, but I agree that the actual best solution is to make sure that the staging/dev envs mirror the live env.

I think I was probably about to shoot myself in the foot by going down the path trying to be smart and serve them at different root paths - so I think the current behaviour is probably the best.

I'll close this issue now so it's off your plate - feel free to re-open later if you see any merit in discussing further.

Thanks 👍
