### ISSUE TITLE
Improvements to Google Sheets translation editing experience

### ISSUE THREAD

**Issue by jeremydw** [grow/grow#384]
- Lock English source cells by default / prevent editing of English source cells
- Highlight cells that are missing translations
- Sidebar containing instructions for editors

/cc @adelaidemt

**Comment by Zoramite** [comment]
For the "Sidebar instructions for editors" Currently the upload only cares about the first three columns, so if you edit it to add in an additional column it should not get overwritten or changed when uploading translations. (maybe put a 10px buffer column between in case we need to use the 4th column in the future?). Instead of having instructions as part of the grow update, it would be better if you can add instructions afterwards.
