### ISSUE TITLE
Stub issue for CMS integration

### ISSUE THREAD

**Issue by jeremydw** [grow/grow#403]
Grow already supports a few ways to ingest content (e.g. from Google Sheets, Contentful, or Blogger), but there should be a stronger integration between Grow documents and collections and CMS files.

Specifically, there should be `up`, `down`, and potentially `sync` flows (commands) for synchronizing Grow content with CMS content, and auto-configuring CMS apps removing the need for a developer to point and click to architect a content type.

A few notes:
- Many CMS support content types or schemas.
- By default, documents in a collection should inherit schemas from their blueprint (which was the original intent behind the name "blueprint" to begin with).
- Documents can specify their own blueprint to override a collection's blueprint.

Some examples:

(WIP)

```
# /content/people/_blueprint.yaml

$fields:
- name: hair_color
- name: age
- name: shirt_size
```

```
# /content/articles/_blueprint.yaml

$fields:
- name: published
- name: quote
```

Content connectors should understand how to synchronize Grow content with CMS content. For example:
-  if a CMS has an image upload tool, Grow should understand how to derive an uploaded image's URL and serialize it into the Grow document.
- if a CMS supports translation, it should be compatible with Grow's translation identifiers.

**Comment by Zoramite** [comment]
One of the things that I added in the kintaro extension that adds a `_schema.yaml` that contains the separated metadata about the bound collection. Then it isn't repeated on each document and doesn't cloud up the `_blueprint.yaml`.

The two-way binding between the systems would be interesting, but I think that would be something that would need to be worked out with the extensions. Maybe an extension hook that would be called whenever a file is changed that would allow for the extension to upload the new data if it knows how?

This would potentially have sync issues since there is no guarantee of the not having changes and is still a shared resource between content managers so it would be easy to accidentally overwrite someone's changes.
