### ISSUE TITLE
File watcher not picking up changes, requiring me to restart the development server for route updates

### ISSUE THREAD

**Issue by jeremydw** [grow/grow#489]
I've noticed that the file watcher doesn't always pick up changes, and then I'm required to restart the development server to pick up updates to YAML file content or the routing tree.

I'm not sure why this is happening but one guess is that there might be too many files to watch in certain situations. For example, I think we should exclude the `build` directory and the `node_modules` directory from being watched.

https://github.com/grow/grow/blob/36ed8b2d21da0ae7cd8dd5140920183b11565112/grow/preprocessors/file_watchers.py#L8

**Comment by jeremydw** [comment]
A quick test shows that the file watcher is working well, but the callback in `on_file_changed` is not updating the right thing when I change the value of `$view`. I need to change the `$path` first, then `$view` is updated.

**Comment by Zoramite** [comment]
That is odd.

The change to the `$view` triggers a [rebuild of the route tree](https://github.com/grow/grow/blob/36ed8b2d21da0ae7cd8dd5140920183b11565112/grow/pods/pods.py#L607-L609). But a normal file change should trigger the [document cache to clear](https://github.com/grow/grow/blob/36ed8b2d21da0ae7cd8dd5140920183b11565112/grow/pods/pods.py#L569-L576) for the specific document.

I remember that we had to change it somewhere to not cache the doc as part of a structure like the routes is doing, but we will probably need to adjust it to [not cache the doc directly in the routes](https://github.com/grow/grow/blob/36ed8b2d21da0ae7cd8dd5140920183b11565112/grow/pods/routes.py#L58) so that the latest from the document cache can be used instead of a cached copy.

**Comment by Zoramite** [comment]
Ahh, yeah, in the `RenderedController` it takes the doc and only stores the `pod_path` and then uses the [pod to get it just in time](https://github.com/grow/grow/blob/master/grow/pods/rendered.py#L41-L45).

**Comment by drGrove** [comment]
I'm noticing this issue with static files as well. When creating and using sourcemaps in dev, a source file may change and it's not reflected on refresh.

**Comment by xtatanx** [comment]
Hello guys,

I am currently using grow to develop a site and we are using gulp + browser sync to speedup development process. Last week noticed that whenever I change a YAML the server reloads but I never see the updated info I need to stop the server and run it again. Also not sure if is related to this but we have some macros that import other macros and if we do changes in the nested macro we do not see them reflected until we save again the parent template. Not too sure how Grow works under the hood but let me know if I can provide some more info in order to help.

Regards

**Comment by Zoramite** [comment]
#504 is adding in support for template dependencies and should also make it so any `extends` and `include` statements in templates correctly track and should trigger the cache reload for them. This issue seems to track a couple of different scenarios that are not refreshing, but we will see if the extra dependency tracking helps.

**Comment by Zoramite** [comment]
Are people still having trouble with needing to restart the server? If you are please open a new issue with more details so we can look into it, there are few reasons you should need to restart the dev server.
