### ISSUE TITLE
Routes can take a while to compute, should use cache

### ISSUE THREAD

**Issue by jeremydw** [grow/grow#490]
Between development server restarts, for large localized sites, the routes can take a while to compute. It would be good to research a way to use a cache for the routes and persist it across development server restarts (potentially using the podcache or otherwise).

**Comment by Zoramite** [comment]
This is mainly because there isn't a `remove` ability for the werkzerg routing. So in order to change the path I have to completely recreate the routing tree to pick up the new changes. I was thinking about subclassing the routing and trying to figure out how to remove a rule. Then we would not need to recreate the entire routing tree when there is a change to the path.

**Comment by Zoramite** [comment]
This should be fixed in the `re-route` option. I'm going to close as I think we are moving to a better system for managing the routes in an efficient way.
