### ISSUE TITLE
Custom preprocessors / plugins

### ISSUE THREAD

**Issue by scisci** [grow/grow#55]
Would be great to be able to write custom preprocessor in python, or jinja extensions, without having to fork the repo. If there was some way to tell grow to add plugins dynamically, would make it much more customizable.

**Comment by stucox** [comment]
The Grow preprocessor class design already suits defining custom processors with whatever parameters the author might want to expose. And of course Jinja extensions are well-defined. Just need a way of telling Grow to import & use them.

Maybe this could start as simple as a `extensions` definition in podspec.yaml, e.g.:

```yaml
extensions:
- extensions.jinja2.ForceEscape
- extensions.preprocessors.ClosureBuilder
```

Grow would just need to:
* Find these classes relative to the pod root (i.e. in `/extensions/jinja2.py` and `/extensions/preprocessors.py` respectively)
* Determine whether each is a Jinja2 extension or Grow preprocessor based on whether they inherit from `jinja2.ext.Extension` or `grow.pods.preprocessors.base.BasePreprocessor` respectively
* Add Jinja extensions to the `extensions` kwarg when creating the Jinja environment
* Call `register_preprocessor()` for each Grow preprocessor

`extensions/` would not need to be a builtin directory name — it’s just probably how I’d structure things in my own projects.

**Comment by stucox** [comment]
Worth noting authors would need to bundle custom Jinja filters into an extension, or Grow would need to provide special syntax for loading them.

**Comment by jeremydw** [comment]
As of January, Grow has supported an extension system, allowing authors to write custom Jinja extensions and custom preprocessors. This, with the ability to pair Grow with Gulp, should hopefully be sufficient here!

http://grow.io/docs/extensions/
http://grow.io/docs/preprocessors/#gulp

**Comment by WillsB3** [comment]
Sorry to comment on an old issue, but not sure where better to ask this question...

I'm experimenting with writing a custom Jinja tag for use in a Grow project. This tag will take an image path and transform it from a regular local image URL to a [proxied URL](https://github.com/imgix/imgix-python#basic-usage) for the image on the image CDN service [imgix](https://www.imgix.com/). However I haven't been able to figure out how to register the tag (e.g. do the equivalent of `environment.filters['triplicate'] = do_triplicate` but for a tag instead of a filter) - can anyone provide any pointers on how to achieve this?

Additionally, my tag would need some configuration (e.g. the sign_key as used [here](https://github.com/imgix/imgix-python#signed-urls) for signing URLs for this imgix account) which I'd prefer to keep out of the extensions .py file in order to keep this reusable across projects, so I was thinking it'd might be a nice idea to be able to store the configuration for the tag in the podspec, but I'm not sure if custom extensions have access to the podspec or if there's a better place to store this project specific config?

Many thanks for any pointers you can provide 👍
