### ISSUE TITLE
"404: /api" warning messages during grow run

### ISSUE THREAD

**Issue by bpaduch** [grow/grow#619]
I've had this issue for awhile (early grow versions and current version) but I would like to get to the bottom of it or at least understand it. 

When I perform a **grow run**, I receive the warning/error of **Error while downloading release information: API rate limit exceeded**, followed by "404: /api" messages that continue as the grow instance runs. Note also that I upgraded Grow from 0.3.8 to 0.3.9 and now I receive the "HTTPNotFound..." messages.

Is it because I don't have OAuth set up for Grow in GitHub?

Grow version: 0.3.9
Environment: Mac and Linux
Docs I build: https://github.com/ampproject/docs

![grow-404-on-mac](https://user-images.githubusercontent.com/1012254/32235369-ac380520-be35-11e7-81cc-94270c6d3be4.png)

**Comment by Zoramite** [comment]
The *Error while downloading release information: API rate limit exceeded* is from grow trying to check for new versions of grow. I am going to be updating that only check every `x` hours which should make that message go away. Not sure what is trying to talk to `/api` that is giving the 404 error.

**Comment by bpaduch** [comment]
I think the 404:/api is related to the API rate exceeds issue.  For two reasons, 1) I can't find any routes for "api" in my pod/docset.  2) I tested it on your [grow.io docs](https://github.com/grow/grow.io), cloned it, ran "grow run" and got the same message:

![selection_006](https://user-images.githubusercontent.com/1012254/32276703-491ce27e-bee6-11e7-8958-833e62b75bc2.png)

**Comment by Zoramite** [comment]
Would you mind trying something? Try closing your normal browser, start the grow server, then open a browser that you normally don't use?

Also you could do `grow run --port: 8085` and check if it still happens when you visit localhost:8085

The error that you are seeing is what happens when a url is being requested locally but is not found in the routes (which is correct). I'm curious if there is a service worker or some plugin or *something* running in your browser that is expecting an `loclahost:8080/api` and keeps requesting it.

**Comment by bpaduch** [comment]
You are correct!  Thank you for figuring that out!
