### ISSUE TITLE
FR: Ability to run grow build for a single language

### ISSUE THREAD

**Issue by bpaduch** [grow/grow#743]
For the [ampproject/docs](https://github.com/ampproject/docs/blob/master/podspec.yaml), we localize the content for 13 diff languages, which means the `grow build` takes a long time.  It'd be useful while testing to spin up grow build for a single language, rather than going through the whole build.  Say, for the `default_locale` or a specific language via a param, something like: 
`grow build locale=en`.

cc: @pbakaus

**Comment by Zoramite** [comment]
Hi @bpaduch 

That is actually something that I have working when using the `--re-route` flag. I was testing it with the [CircleCI build](https://circleci.com/workflow-run/473d49ca-486b-4ab4-8bd1-6f345350bdf7).

For example:

`grow build --re-route --locale None --locale ar --locale de --locale en`

Since the rendering with jinja doesn't react very well to threading this was one of the options to speed things up–splitting up the build into separate builds then combining the results which you can see in the [workflow](https://circleci.com/workflow-run/473d49ca-486b-4ab4-8bd1-6f345350bdf7) I was working on for the amp docs.

**Comment by bpaduch** [comment]
So, is this in progress?  I'd like to be able to use the option primarily for local builds.

**Comment by Zoramite** [comment]
It should be working now, try `grow build --re-route --locale None --locale en` to test it out.

The `--locale None` is needed so that the things without a locale are built as well.

**Comment by bpaduch** [comment]
Cool, I tried it and the content built but failed to deploy [see error on gist ](https://gist.github.com/bpaduch/582d3e58ec060f6afdbf272fa7124131).

**Comment by Zoramite** [comment]
Oh, I had to add this [fix for the blog page](https://github.com/Zoramite/docs/commit/17921fe857b7e99a7525d00fc4d558d05be44793) when I was testing since the `--re-route` had trouble with the path collision.
