### ISSUE TITLE
New Routing Not Recognizing Paths in Collection

### ISSUE THREAD

**Issue by ViktorZharina** [grow/grow#778]
My blog based on grow https://github.com/ViktorZharina/static-blog-based-on-grow.
I update to the latest version of grow and got the problem. My old routes is not worked. Only main pages and site map.
Adding --old-routing flag fixed it but as I understand it is deprecated.
Is http://grow.io/docs/urls/ a topical info about new route system? Where can I read about it?

**Comment by Zoramite** [comment]
Thanks for the input and example. The new routing should–for the most part–be something that you shouldn't really notice.. unless it breaks :)

I'll check out this issue more tomorrow and see if we can get a fix in for the next release.

**Comment by Zoramite** [comment]
@ViktorZharina I think that this mostly has to do with your file structure of the content.

Grow doesn't recognize `/content/ru/post@ru.md` as being the same (localized) document as `/content/en/post@en.md`.

I would suggest putting all of your posts in a single directory and keeping the file names the same except for the localized portion.

For example, keep your content files like this: 

```
/content/posts/2018-05-06-09-43-54-Highload-2017-vs-Codefest-2018@en.md
/content/posts/2018-05-06-09-43-54-Highload-2017-vs-Codefest-2018@ru.md
```

Grow would recognize those as two localized version of the same document and the routes will not have the same issues building the structure.

**Comment by ViktorZharina** [comment]
Thanks. I did this structure because old routing system recognized it. This file structure seems to me more convenient than mix all lang in one folder. As I understood new routing system will never support this structure?

**Comment by Zoramite** [comment]
So the new routing world uses two different styles of routing: an abstract/trie based routing, and a simple routing.

The trie based routing is used for the development server when running on large sites that have many locales.

The simple routing is used when building/deploying as it enumerates out all the specific pages. But for development this is slower on large websites since you have to enumerate every locale and page.

We won't support split locales in the trie based because it makes the lookup of locale alternatives even more complicated. An alternative that we could look at would be to make a setting for using the fully enumerated routing work on the dev server, which would give you similar results without the extra 
routing logic.
