### ISSUE TITLE
Document that doesn't have locales reports "too many parts"

### ISSUE THREAD

**Issue by vitorio** [grow/grow#795]
I have a Markdown document where I'm using some separate JS formatters instead of the built-in ones, and I have an HTML bit that looks like this: 

```html
<pre class="command-line language-bash" data-prompt="pm3 -->" data-output="2-17"><code>hf mf nested 0 4 A 6dd747e86975

-----------------------------------------------
Iterations count: 0</code></pre>
```

This immediately throws the error of:

```
BadFormatError: Document contains too many parts: ,
    Please run `grow convert --type content_locale_split` to help update files.
```

Seems like whatever locale "parts" parsing happens pretty early?  I'm currently correcting for this by putting whitespace in front of that whole section, but is there another way?

**Comment by Zoramite** [comment]
This is happening because the markdown is located in the `content/` directory. It sounds like you don't want it to be parsed by the python markdown though. I'm not sure how you are getting it to the JS formatter to be parsed, but I would suggest putting it into a static directory outside of the `content/` so that the JS can load it without it being parsed as a Grow document. Then your JS can parse and use it how you want without Grow trying to look for front matter and processing it as markdown.

**Comment by Zoramite** [comment]
And the error about too many parts is actually because it has the `---` line in it. The front matter looks for those as a delimiter to parse out the front matter from the actual md content.

**Comment by vitorio** [comment]
Doing these console dumps as includes makes sense as an alternative, thanks for it.

To be clear, --- is always used to separate the front matter, so I should never expect to have that as its own line in Markdown content, because it'll be split out?  Is this just for Markdown content, or for HTML content also?

**Comment by Zoramite** [comment]
Yeah, currently we split the lines based on the presence of `---` in the beginning of the line. And we have logic in the front matter so that if it finds more sections than it expects it throws an error. (An older version of grow used to allow multiple sections of front matter). We use the presence of too many sections as an indicator that it is looking at an old formatted file and that the user needs to upgrade their content to the newer version.

And this happens on every document type in the `content/` directory that allows front matter. Which mean everything except `.yaml` files. So if you have html documents then they would be restricted to not have extra lines starting with `---`.
