### ISSUE TITLE
Make URL changes easier by adding ability to maintain redirects/alternate URLs in collections

### ISSUE THREAD

**Issue by jeremydw** [grow/grow#8]
To make URL changes easier, add the ability for content documents and collections to specify a list of alternate URLs (paths) that redirect to the canonical URL for the content.

Example of a URL change:

```
#1: /content/pages/_blueprint.yaml
path: /foo/{slug}/

#2:  /content/pages/_blueprint.yaml
path: /site/foo/{slug}/
redirects:
- path: /foo/{slug}/
```

For a page whose slug is "bar", when (2) is deployed, requests to /foo/bar/ will be redirected to /site/foo/bar/. When site owners decide the redirects are no longer necessary, they can be easily removed from the blueprint without hunting down the origin/reason behind the URL change/redirect.

**Comment by ciampo** [comment]
Hey @jeremydw , is there any update on this feature?

On one of my projects, I need to redirect to the homepage from another URL. This feature looks like exactly what I need.

**Comment by jeremydw** [comment]
Hello @ciampo - we don't have any built-in redirect behavior yet that integrates with any deployment target, but in the meantime what you can do is implement a client side redirect like so:

```
# /content/pages/old.html
$path: /old/
$view: /views/redirect.html
redirect_to: /new/
```

```
# /views/redirect.html

<!doctype html>
<title></title>
<script>window.location = '{{doc.redirect_to}}';</script>
```

Note that this is a client-side redirect, so the HTTP response code will still be 200; the proper way to do this would be to configure your server to return a 302 response code with the right `Location` header.

**Comment by falkben** [comment]
just wanted to put forth another alternative, in my case i want two paths to render the same content:

```
# /content/pages/old.html
---
$title@: TITLE (could be the same as new.html)
---

<!-- we use content from the other page to do the render -->
{% set doc=g.doc('/content/OTHER_COLL/OTHER_PAGE.html') %}

<!-- this partial is also called from the "new" page's view -->
{% include 'partials/COMMON_PARTIAL.html' %}
```

this seemed to minimize the amount of duplicated code

I found that i had to use this include to call the "view" code because otherwise the view wouldn't have access to the content from the "new" page

**Comment by Zoramite** [comment]
I think that the idea of grow directly handling redirects isn't really in the scope of what we want grow to do. This effect can be achieved by a JS redirect using a custom view, etc. and since grow builds the static files and doesn't serve them in production, there isn't anything that grow intrinsically can do when you deploy it other then render some redirect js pages.
