### ISSUE TITLE
Flag check on/off for existing static files

### ISSUE THREAD

**Issue by ViktorZharina** [grow/grow#825]
Before: I have lighweight static content but today I want to add a lot photos to my blog. 
Problem: Uploading static content is taking much time now.
Drscription
I have an images in /source/images/ dir. When I deploy these images upload to a server. It takes much time. I tryied to remove images from /source/images and in deploy script set symlink to images after deploy. So I don't have image ib source/images dir  and avoid long uploading. Sound good but checks in grow build command prevent it because I have a links in a post. 
Maybe there is a glag that switch off these checks or you can give me advice to avoid long uploading due to heavyweight images content.
Thanks for your answers.

**Comment by Zoramite** [comment]
We don't have a way for disabling the static file upload for now. Since we do a diff against the last deployed files and the current set it should only need to upload the static file one time. Then each new build, as long as the static file hasn't changed, the file should not be uploaded.

Do you add a lot of static files with each commit, or is it the original upload that takes the most time?

One idea would be do create an extension that would be able to reference external images, such as on GCS. 

With sites that have a lot of images we often use the [GCI extension](https://github.com/grow/grow-ext-google-cloud-images) that allows us to upload the files to Google Cloud Storage and then using them in our projects with the ability to resize and crop them using different parameters.
