### ISSUE TITLE
Grow crashes when "%" is in any msgstr in messages.po

### ISSUE THREAD

**Issue by pbakaus** [grow/grow#831]
The latest version of Grow crashes and fails to build as soon as it finds a percentage sign in any translated string originating in a messages.po file (that is used on the current page).

**Comment by Zoramite** [comment]
Hi @pbakaus this is because of the gettext (`_()`) uses the old style python formatting to format strings. So when there is a `%` it needs to be escaped (`%%`). I'm working on #846 that would remove the old formatting by default so that string formatting would need to use the newer formatting (`Test out {name} in {text}`) instead of the older python formatting (`Test out %(name)s in %(text)s`).

If everything looks good then the next version of grow will have it as a breaking change (since some projects do use that style of formatting) with the ability to use the old formatting in the podspec settings.

**Comment by pbakaus** [comment]
ah interesting, thanks for digging into this! Super useful to know.

**Comment by Zoramite** [comment]
The latest version set the default for string formatting to not use the old format, so hopefully this isn't an issue anymore.
