### ISSUE TITLE
Heroku hosting / deployment

### ISSUE THREAD

**Issue by josephwilliams** [grow/grow#873]
Heroku is a popular cloud hosting platform typically used for dynamic sites but that can also, with a heroku buildpack and some configuration, host static sites. 

A direct integration with this PaaS would be useful, or grow-specific heroku buildpack, or, short of that, documentation in the [grow.io deployment setup page](http://grow.io/docs/deployment/) regarding build configuration and deployment/hosting via Heroku.

**Comment by Zoramite** [comment]
This sounds like it would be a good use for an extension. I know that we have made custom deployment integrations as extensions before. I don't think we have done anything for heroku yet.

**Comment by jeremydw** [comment]
FYI – We're moving away from building in deployment options to Grow and relying on users to determine their own deployment options. Since Grow is generating static files, the idea is that a static set of files can be generated, and then deployed to Heroku in a separate build step.

For example:

```
grow build
# command to deploy a heroku static site, loading files from the ./build/ directory
```

This concept works with other hosting providers such as Netlify as well:
https://www.netlify.com/blog/2016/10/27/a-step-by-step-guide-deploying-a-static-site-or-single-page-app/

If you are interested in a static server that has some dynamic features sprinkled on top (redirects, etc.), the Grow team maintains a static server called Fileset that is deployed on GCP:
https://github.com/blinkkcode/fileset
