### ISSUE TITLE
Path formatting "/{base}.html" does not work for index document

### ISSUE THREAD

**Issue by tharders** [grow/grow#930]
If we have a `_blueprint.yaml` with the following:

```
$path: /foo/{base}.html
$localization:
  path: /intl/{locale}/foo/{base}.html
````
An `index.md` document in this folder will not be available at all.
You have to specify the path explicitly for the index document as a work around.

This problem was introduced with the changes for the issue https://github.com/grow/grow/issues/915

Maybe it would be best to remove the `index` only if the path ends with `/{base}` or `/{base}/`

**Comment by matthiasrohmer** [comment]
Thanks @tharders for reporting this! 🙂This occurs in ampproject/docs. Background is that we've appended `.html` to all `$paths` because we need Grow to write proper HTML files with a file extension for a later gulp task to be able to properly handle those files.

*But* as we also want fancy URLs without extension nor `index` in the rendered HTML we we're relying on an ugly monkey-patch that we injected via the extension mechanism:

https://github.com/ampproject/docs/blob/7a3f70b6dc0815fbb4fd875cc55b75b6383b6e2f/pages/extensions/url_beautifier/url_beautifier.py#L1-L15
