### ISSUE TITLE
Unable to access localized lists of strings.

### ISSUE THREAD

**Issue by meizon** [grow/grow#95]
If I put a list of localized strings in YAML:

```
flavors@:
  - lemon
  - mango
  - raspberry
```

I am unable to access these using `doc.flavors` instead I have to do `doc['flavors@']`

**Comment by jeremydw** [comment]
This was (finally) fixed in https://github.com/grow/grow/commit/ec4f063dca31c5b6cedcfe7e24f25b2241deba75

**Please note**! If you were previously using `{{doc['flavors@']}}` before to access strings from a list whose key ends in `@`, you'll now have to use `{{doc.flavors}}` as normal.

@stucox and @meizon I'd like your opinion on this as it's a breaking change. Unfortunately Jinja silently fails if you access `{{doc['flavors@']}}` and `flavors@` doesn't exist in the key.

So we have two options, I think, and neither are ideal but let me know what you think.

1. Be backwards compatible on this by duplicating any tagged lists that may exist in the yaml. This isn't ideal from a performance or code simplicity standpoint but it is doable. The content file would then have two entries per tagged list -- one with the tag and one without the tag.
1. Let this break and communicate in the release notes and email lists about this change.

**Comment by jeremydw** [comment]
Okay, I was able to fix this with (1). Our fix is now backwards compatible with the previous behavior, and leaves tagged lists as tagged (but also duplicates them, so you can access the data in your example as `{{doc.flavors}}` instead of `{{doc['flavors@']}}`.

**Comment by meizon** [comment]
I assume there will be a deprecation warning / policy for removing the doc['flavors@'] method?

**Comment by jeremydw** [comment]
We're actually backwards compatible now (and I verified with existing sites), so deprecation warning isn't necessary at the moment since the previous behavior will continue to work. :)
